services:
  mysql:
    image: mysql:8.0
    container_name: bumimedika-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bumimedika-network

  # redis:
  #   image: redis:7-alpine
  #   container_name: bumimedika-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - bumimedika-network

  # app:
  #   build: .
  #   container_name: bumimedika-backend
  #   restart: unless-stopped
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - bumimedika-network

volumes:
  mysql_data:

networks:
  bumimedika-network:
    driver: bridge
